[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sigma-anywidget"
dynamic = ["version"]
description = ''
readme = "readme.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Ethan Rooke", email = "pypi@ethan.roo.ke" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "anywidget (>=0.9.0,<1.0.0)"
]

[project.urls]
Documentation = "https://github.com/Ethan Rooke/sigma-anywidget#readme"
Issues = "https://github.com/Ethan Rooke/sigma-anywidget/issues"
Source = "https://github.com/Ethan Rooke/sigma-anywidget"

[tool.hatch.version]
path = "src/sigma_anywidget/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
